<?php
/**
 * Created by PhpStorm.
 * User: LaravelDude
 * Date: 1/9/16
 * Time: 10:22 PM
 */

namespace App\Tools\Pages;


class Slug
{
    protected $slugToSku = [
        "30-day-quick-weight-loss-plan-supplements-for-men-free-testosterone"=>[
            "sku"=>'30D-WLC-MPL',
            "id"=>235
        ],
        "30-day-quick-weight-loss-plan-supplements-for-women-m"=>[
            "sku"=>'30DM-WLC-F',
            "id"=>549
        ],
        "30-day-quick-weight-loss-plan-supplements-for-women-m2"=>[
            "sku"=>'30DM-WLC-F2',
            "id"=>700
        ],
        "30-day-quick-weight-loss-plan-free-testosterone-supplements-for-men-level-2"=>[
            "sku"=>'30DM-WLC-M2',
            "id"=>700
        ],
        "30-recipes-under-300-calories"=>[
            "sku"=>'30RU300C',
            "id"=>700
        ],
        "4-pack-ebook-bundle-recipe-books"=>[
            "sku"=>'4SHKCHEB',
            "id"=>700
        ],
        "4-pack-ebook-bundle-plus-thermogenic-protein"=>[
            "sku"=>'4SKEB-TPRO-VA',
            "id"=>700
        ],
        "alpha-female-black-and-gold-tanktop"=>[
            "sku"=>'AFGOLD-BL-S',
            "id"=>700
        ],
        "alpha-female-neon-green-hand-printed-tanktop"=>[
            "sku"=>'AFNEON-GR-S',
            "id"=>700
        ],
        "alpha-female-neon-pink-hand-printed-tanktop"=>[
            "sku"=>'AFNEON-PK-S',
            "id"=>700
        ],
        "alpha-female-neon-yellow-hand-printed-tanktop"=>[
            "sku"=>'AFNEON-YL-S',
            "id"=>700
        ],
        "alpha-female-plan-plus-supplements-for-her"=>[
            "sku"=>'',
            "id"=>700
        ],
        "alpha-female-plan-plus-supplements-for-her"=>[
            "sku"=>'AFP-1M-30DSC-BM',
            "id"=>700
        ],
        "alpha-male-plan-supplements-for-him"=>[
            "sku"=>'AM-J-1M',
            "id"=>700
        ],
        "alpha-male-stringer-black-red"=>[
            "sku"=>'AMS-BR-S',
            "id"=>700
        ],
        "alpha-male-stringer-white-black"=>[
            "sku"=>'AMS-WB-S',
            "id"=>700
        ],
        "shredz-bcaa-glutamine-fruit-punch-men"=>[
            "sku"=>'BCGL-M-FP-MM',
            "id"=>700
        ],
        "shredz-bcaaglutamine-fruit-punch-women"=>[
            "sku"=>'BCGL-W-FP-MM',
            "id"=>700
        ],
        "shredz-protein-2lb"=>[
            "sku"=>'CHPB-2LB-1M',
            "id"=>700
        ],
        "shredz-protein-1lb"=>[
            "sku"=>'CNBN-1LB-1M',
            "id"=>700
        ],
        "core-burner-max"=>[
            "sku"=>'COREBMX-1M',
            "id"=>700
        ],
        "shredz-creatine"=>[
            "sku"=>'CORECR-1M',
            "id"=>700
        ],
        "shredz-burner"=>[
            "sku"=>'COREFB-1M',
            "id"=>700
        ],
        "shredz-detox"=>[
            "sku"=>'COREMV-1M',
            "id"=>700
        ],
        "shredz-testosterone"=>[
            "sku"=>'CORETB-MM',
            "id"=>700
        ],
        "shredz-female-crop-hoodie-black-red"=>[
            "sku"=>'CRPHD-BR-S',
            "id"=>700
        ],
        "shredz-female-crop-hoodie-white-pink"=>[
            "sku"=>'CRPHD-WP-S',
            "id"=>700
        ],
        "dotd-30-day-quick-weight-loss-plan-for-men-plus-supplement-free-gift-max"=>[
            "sku"=>'DOTD-30DDBRSTS',
            "id"=>700
        ],
        "dotd-30-day-quick-weight-loss-plan-for-women-plus-supplements-plus-free-gift-max"=>[
            "sku"=>'DOTD-30DFM-DBPNKS',
            "id"=>700
        ],
        "dotd-30-day-quick-weight-loss-plan-for-women-plus-supplements-plus-free-gift-max"=>[
            "sku"=>'EB-JS-THTM-V1',
            "id"=>700
        ],
        "sexy-beautiful-stack-for-her-burner-detox-beauty"=>[
            "sku"=>'FF-1M',
            "id"=>700
        ],
        "fat-loss-blue-print-free-slim-waist-and-butt-sculpting-program"=>[
            "sku"=>'FLBP-SW-BSP',
            "id"=>700
        ],
        "6-pack-plan-for-him-supplements"=>[
            "sku"=>'MC-1M',
            "id"=>700
        ],
        "shredz-beauty-for-women"=>[
            "sku"=>'MFWAA-1M',
            "id"=>700
        ],
        "shredz-burner-max-made-for-women"=>[
            "sku"=>'MFWBMX-1M',
            "id"=>700
        ],
        "shredz-toner-for-women"=>[
            "sku"=>'MFWCR-1M',
            "id"=>700
        ],
        "shredz-burner-for-women"=>[
            "sku"=>'MFWFB-1M',
            "id"=>700
        ],
        "shredz-detox-for-women"=>[
            "sku"=>'MFWMV-1M',
            "id"=>700
        ],
        "shredz-preworkout-mango"=>[
            "sku"=>'PP-MA-1M',
            "id"=>700
        ],
        "shredz-rebuild-pm-for-women"=>[
            "sku"=>'RBPM-F-MM',
            "id"=>700
        ],
        "shredz-rebuild-pm"=>[
            "sku"=>'RBPM-M-MM',
            "id"=>700
        ],
        "alex-michael-turners-guide-to-aesthetics"=>[
            "sku"=>'SH-EB-AMTGTA',
            "id"=>700
        ],
        "devin-physiques-formula-for-abs"=>[
            "sku"=>'SH-EB-DVN-ABS',
            "id"=>700
        ],
        "six-pack-blueprint-for-men-english"=>[
            "sku"=>'SH-EB-SPBP',
            "id"=>700
        ],
        "ifbb-pro-tristen-esos-gains-guide"=>[
            "sku"=>'SH-EB-TEGG',
            "id"=>700
        ],
        "shredz-shaker"=>[
            "sku"=>'SHAKERCUP-RR',
            "id"=>700
        ],
        "shredz-dumbbell-fashion-bracelet-red"=>[
            "sku"=>'SHDFB-RED-M',
            "id"=>700
        ],
        "shredz-rocket-red-shorts"=>[
            "sku"=>'SHORTS-RR-S',
            "id"=>700
        ],
        "shredz-ultra-pink-shorts"=>[
            "sku"=>'SHORTS-UP-S',
            "id"=>700
        ],
        "shredzarmy-rocket-red-sports-bra-leggings"=>[
            "sku"=>'SHSBLGSRR-SS',
            "id"=>700
        ],
        "shredzarmy-ultra-pink-sports-bra-leggings"=>[
            "sku"=>'SHSBLGSUP-SS',
            "id"=>700
        ],
        "30-recipes-under-300-calories-plus-weight-loss-smoothies"=>[
            "sku"=>'SKEB-30U300-WLS',
            "id"=>700
        ],
        "sexy-and-lean-plan-plus-supplements-for-her"=>[
            "sku"=>'SLP-1M',
            "id"=>700
        ],
        "shredz-pink-leggings-sports-bras"=>[
            "sku"=>'SLSB-PK-SXS',
            "id"=>700
        ],
        "shredz-red-leggings-sports-bras"=>[
            "sku"=>'SLSB-RD-SS',
            "id"=>700
        ],
        "shredz-rocket-red-sports-bra"=>[
            "sku"=>'SPRTBRA-RR-S',
            "id"=>700
        ],
        "shredz-ultra-pink-sports-bra"=>[
            "sku"=>'SPRTBRA-UP-S',
            "id"=>700
        ],
        "shape-and-tone-plan-plus-supplements-for-her"=>[
            "sku"=>'STP-F-1M',
            "id"=>700
        ],
        "shredz-thermogenic-protein-made-for-women-blueberry-2lb"=>[
            "sku"=>'TPRO-BM-2LB-MM',
            "id"=>700
        ]
    ];

    public function getSku($slug)
    {
        $slug = $this -> slugToSku[$slug];
        return $slug['sku'];
    }

    public function getId($slug)
    {
        $slug = $this -> slugToSku[$slug];
        return $slug['id'];
    }
}


